Fix:
```
gulpfile.ts:159:24 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(globs: string | string[], fn?: TaskFunction): FSWatcher', gave the following error.
    Argument of type '() => Undertaker.TaskFunction' is not assignable to parameter of type 'TaskFunction'.
      Type 'TaskFunction' is not assignable to type 'void | EventEmitter | ChildProcess | Stream | Observable<any> | PromiseLike<any>'.
        Property 'then' is missing in type 'TaskFunction' but required in type 'PromiseLike<any>'.
  Overload 2 of 2, '(globs: string | string[], opts?: WatchOptions, fn?: TaskFunction): FSWatcher', gave the following error.
    Type '() => TaskFunction' has no properties in common with type 'WatchOptions'.

159   gulp.watch(src.html, () => gulp.series(html, reload));
```